### PR TITLE
Fix for navigation issues

### PR DESCRIPTION
**Pull request by ashtonlance**
#21, #16 , #24

### CODE REVIEW

**Comment by ashtonlance** [comment]
@replaid -- new code here for directory fixes

**Comment by replaid** [comment]
Hi @ashtonlance, thanks much. Can you remove the `gh-pages` commits from this PR?

**Comment by ashtonlance** [comment]
Sure thing! Reverted merge above.

**Comment by replaid** [comment]
Thanks so much @ashtonlance!

**Pull request merged**
